- name:  Download client configs to the "wireguard_role/profiles/" folder on your local host
  fetch:
    src: "~/wg_clients/client_1/wg0-client.conf"
    dest: "{{ client_config_path }}/wg{{ansible_play_batch.index(inventory_hostname)}}.conf"
    flat: yes
  tags: "wg_fetch"